name: Build and Release KernelSU

on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: rm -rf ${PWD}/*

      - name: Set-up environment
        run: |
          mkdir kernel
          cd kernel
          git clone https://github.com/dogpoopy/android_kernel_xiaomi_vayu.git -b kernelsu --depth=1 .
          sudo apt-get update
          sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev
          sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache python2 python2-dev
          sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar cpio jq

      - name: Build
        run: |
          cd kernel
          bash ksu.sh

      - name: Retrieve latest KernelSU tag and zip file name
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          zip_file=$(find $HOME -name 'Spoliarium*.zip' -print -quit)
          echo "ZIP_FILE=$zip_file" >> $GITHUB_ENV
          echo "ZIP_NAME=$(basename "$zip_file" .zip)" >> $GITHUB_ENV

      - name: Upload to repository releases page
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_FILE }}
          name: ${{ env.ZIP_NAME }}
          tag_name: ${{ github.run_id }}
          body: |
            KernelSU version: ${{ env.LATEST_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
